site_name: COYANG
site_url: https://coyang.top/
site_description: Coyang's Personal Blogs

repo_name: Coyang's Blogs
site_author: coyang
docs_dir: docs

plugins:
  - search
  - mermaid2
  - mkdocs-video
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0
  - build_plantuml:
      render: 'local' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'images'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed

markdown_extensions:
  - attr_list
  - smarty
  - toc:
      permalink: True
  - sane_lists

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

theme:
    name: material
    logo: images/logo/COYANG-logos_white.png
    favicon: images/logo/COYANG-logos_transparent.png
    font: false
    features:
        - navigation.instant
        - navigation.tabs
        - navigation.top
        - navigation.prune
        - search.highlight
        - search.suggest
        - content.code.annotate
        - content.code.copy
    shortcuts:
        help: 191    # ?
        next: 78     # n
        previous: 80 # p
        search: 83   # s
    highlightjs: true
    hljs_languages:
        - yaml
        - django
        - rust
        - json
        - python
        - diff
        - java

nav:
  - Home: index.md
  - AIGC: aigc/index.md
  - Knowledge: knowledge/index.md
  - English Learning: english_learning/index.md
  - Musings of the individual: musings/index.md
  - About: about/index.md
