site_name: COYANG
site_url: https://coyang.top/
site_description: Coyang's Personal Blogs

repo_url: https://github.com/coyang/blogs
repo_name: https://github.com/coyang/blogs
site_author: coyang
docs_dir: docs

plugins:
  - search
  - mermaid2
  - mkdocs-video
  - markmap:
      base_path: docs
      encoding: utf-8
      file_extension: .mm.md
      d3_version: 6.7.0
      lib_version: 0.14.1
      view_version: 0.14.0
  - build_plantuml:
      render: 'local' # or "local" for local rendering
      bin_path: '/usr/local/bin/plantuml' # ignored when render: server
      server: 'http://www.plantuml.com/plantuml' # official plantuml server
      disable_ssl_certificate_validation: true # for self-signed and invalid certs
      output_format: 'svg' # or "png"
      diagram_root: 'docs' # should reside under docs_dir
      output_folder: 'out'
      input_folder: 'images'
      input_extensions: 'puml' # comma separated list of extensions to parse, by default every file is parsed

markdown_extensions:
  - attr_list
  - smarty
  - toc:
      permalink: True
  - sane_lists

extra_javascript:
    - https://unpkg.com/mermaid/dist/mermaid.min.js

theme:
    name: readthedocs
    highlightjs: true

nav:
  - Home: index.md
  - Musings of the individual:
    - My First Blog: musings/first_blog.md
    - FEYNMAN TECHNIQUE : musings/feynman_technique.md
  - Notes:
    - How to register domain name: web/how_to_apply_domain_name.md
  - Skill: personal/skill.md
  - Performance tuning tools: performance/performance_tuning_tools.md
