gantt
    title Career Path
    dateFormat  YYYY-MM
    axisFormat  %Y-%m

    section 上海诺基亚贝尔股份有限公司
    全栈工程师          :Nokia, 2011-08, 2025-04

    section 杭州国芯科技股份有限公司
    嵌入式软件工程师    :NathonalChip, 2010-05, 2011-07

    section 东软集团（大连）有限公司
    嵌入式软件工程师    :Neusoft, 2008-09, 2010-04

    section 教育经历
    山东科技大学 本科    :edu, 2004-09, 2008-06
