mindmap
  root((COYANG's Skill Map))
    AI
      Common knowledge
        LLM
        Inference
        Training
        Fine-tuning
        Agent
        RAG
        Prompt Engineering
      Frameworks
        PyTorch
        TensorFlow
        Transformers
      Machine Learning

      Data Skills

      Model host
        Ollama
        vLLM
        Hugging Face
      Deployment Frameworks
        Langchain
        CrewAI
        LlamaIndex
        Coze / Dify
    Agile
      Scrum
      DevOps

    Development
      Programming Languages
        C / C++
        Golang
        Python
        Shell
        TypeScript
    Basic knowledge
      Operating System
      Data structure and Algorithm
      RegExp
      Makefile
      Container
      Network
      Storage
          Shadows
          GlusterFS
      DB

    Infrastructure
      OpenStack
      Kubernetes
        Helm
        Kubernetes architecture

    Testing
      Unit testing
      Integration testing
      Contract Testing
      Robotframework

    Clean code
      Quality
        Code format
        Static analysis

    Documentation
    DTV
    Front End
